---
name: CI

on: [push, pull_request]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

          # Only block PRs on new problems.
          # If this is not enabled, we will end up having PRs
          # blocked because new linters has appared and other
          # parts of the code is affected.
          only-new-issues: true

  prettier-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prettify code
        uses: creyD/prettier_action@v4.0
        with:
          prettier_options: >-
            --check **/*.{ts,js,md,yaml,yml,sass,css,scss,html}
          only_changed: false
          dry: true

  proto-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v0.7.0
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: "proto"
